server {
    listen 80 default_server;
    server_name 172.236.139.122;
    location /.well-known/acme-challenge/ { root /var/www/kentech-acme; }
    location / { return 301 https://172.236.139.122$request_uri; }
}
server {
    listen 443 ssl;
    server_name 172.236.139.122;
    ssl_certificate /etc/letsencrypt/live/172.236.139.122/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/172.236.139.122/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    client_max_body_size 256k;
    add_header X-Content-Type-Options nosniff always;
    add_header Referrer-Policy no-referrer always;
    location / {
        proxy_pass http://127.0.0.1:3100;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto https;
        proxy_read_timeout 60s;
    }
    location /api/ {
        access_log off;
        proxy_pass http://127.0.0.1:3100;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto https;
        proxy_read_timeout 60s;
    }
}
