const { test } = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { EventEmitter } = require('node:events')
const { createGuard } = require('../download-group-guard')

const group = '123@g.us'
const other = '456@g.us'
const sender = '200@s.whatsapp.net'
const socket = { user: { id: '100:2@s.whatsapp.net', lid: '101@lid' } }
const raw = (overrides = {}) => ({ key: { remoteJid: group, participant: sender, id: '3EB0123456789012345678', ...overrides }, message: { conversation: 'download ready' } })
function setup(t) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'botguard-test-'))
  fs.writeFileSync(path.join(root, 'auto-download-groups.json'), JSON.stringify([group]))
  t.after(() => fs.rmSync(root, { recursive: true, force: true }))
  return { root, guard: createGuard(root) }
}

test('detects bot replies only in protected groups and exempts the owner', t => {
  const { guard } = setup(t)
  assert.equal(guard.shouldBlock(raw(), socket), true)
  assert.equal(guard.shouldBlock(raw({ remoteJid: other }), socket), false)
  assert.equal(guard.shouldBlock(raw({ fromMe: true }), socket), false)
  assert.equal(guard.shouldBlock(raw({ participant: '101@lid' }), socket), false)
  assert.equal(guard.shouldBlock(raw({ participant: '100@s.whatsapp.net' }), socket), false)
})

test('ordinary group members can still post download links', t => {
  const { guard } = setup(t)
  const message = raw({ id: 'NORMALPHONE123' })
  message.message.conversation = 'https://vt.tiktok.com/ZSqFGMM6Y/'
  assert.equal(guard.shouldBlock(message, socket), false)
})

test('detected senders remain blocked after restart, with a persistent release override', t => {
  const { guard, root } = setup(t)
  guard.shouldBlock(raw({ participantAlt: '201@lid' }), socket, true)
  const restarted = createGuard(root)
  assert.equal(restarted.shouldBlock(raw({ id: 'NORMALPHONE123' }), socket), true)
  restarted.configure(group, 'release', [sender, '201@lid'])
  assert.equal(createGuard(root).shouldBlock(raw(), socket), false)
  restarted.configure(group, 'block', [sender])
  assert.equal(restarted.shouldBlock(raw(), socket), true)
})

test('release-all disables enforcement and on restores it', t => {
  const { guard, root } = setup(t)
  guard.configure(group, 'off')
  assert.equal(createGuard(root).shouldBlock(raw(), socket), false)
  guard.configure(group, 'on')
  assert.equal(guard.shouldBlock(raw(), socket), true)
})

test('deletes new bot messages silently, without replaying history or touching own video', async t => {
  const { guard } = setup(t)
  const deleted = []
  const live = { ...socket, ev: new EventEmitter(), sendMessage: async (jid, payload) => deleted.push({ jid, payload }) }
  guard.attach(live)
  live.ev.emit('messages.upsert', { type: 'append', messages: [raw()] })
  live.ev.emit('messages.upsert', { type: 'notify', messages: [raw(), raw({ fromMe: true }), raw({ remoteJid: other })] })
  await new Promise(resolve => setImmediate(resolve))
  assert.equal(deleted.length, 1)
  assert.deepEqual(deleted[0].payload, { delete: { ...raw().key, fromMe: false } })
})

test('bot captions are detected inside wrapped video messages', t => {
  const { guard } = setup(t)
  const message = raw({ id: 'NORMALPHONE123' })
  message.message = { ephemeralMessage: { message: { videoMessage: { caption: 'VIDEO GENERATED BY OTHER BOT' } } } }
  assert.equal(guard.shouldBlock(message, socket), true)
})


test('deletes native non-admin group statuses, preserving admins and own posts', async t => {
  const { guard } = setup(t)
  const deleted = []
  const live = {
    ...socket, ev: new EventEmitter(),
    groupMetadata: async () => ({ participants: [
      { id: sender, admin: null }, { id: '300@lid', admin: 'admin' },
      { id: '100@s.whatsapp.net', admin: 'admin' },
    ] }),
    sendMessage: async (jid, payload) => deleted.push({ jid, payload }),
  }
  guard.attach(live)
  const status = (id, participant = sender, wrapper = 'groupStatusMessageV2') => ({
    key: { remoteJid: group, participant, id },
    message: { [wrapper]: { message: { imageMessage: {} } } },
  })
  live.ev.emit('messages.upsert', { type: 'notify', messages: [
    status('member-v2'), status('member-v1', sender, 'groupStatusMessage'),
    status('3EB0123456789012345678', '300@lid'),
    { ...status('own'), key: { ...status('own').key, fromMe: true } },
    { ...status('other-group'), key: { ...status('other-group').key, remoteJid: other } },
    { ...status('personal'), key: { ...status('personal').key, remoteJid: 'status@broadcast', statusJidList: [group] } },
  ] })
  await new Promise(resolve => setImmediate(resolve))
  assert.equal(deleted.length, 2)
  assert.ok(deleted.every(item => item.jid === group))
  assert.deepEqual(deleted.map(item => item.payload.delete.id), ['member-v2', 'member-v1'])
})

test('fails open on missing sender metadata and respects botguard off', async t => {
  const { guard } = setup(t)
  const status = raw({ id: 'native-status' })
  status.message = { ephemeralMessage: { message: { groupStatusMessageV2: { message: { videoMessage: {} } } } } }
  const live = { ...socket, groupMetadata: async () => ({ participants: [] }) }
  assert.equal(await guard.shouldDeleteGroupStatus(status, live), false)
  live.groupMetadata = async () => ({ participants: [{ id: sender, admin: null }] })
  assert.equal(await guard.shouldDeleteGroupStatus(status, live), true)
  guard.configure(group, 'off')
  assert.equal(await guard.shouldDeleteGroupStatus(status, live), false)
})

test('sends one KENTECH AI startup message per connected account', async t => {
  const { guard } = setup(t)
  const sent = []
  const live = {
    ...socket,
    user: { id: 'startup-test@s.whatsapp.net' },
    ev: new EventEmitter(),
    sendMessage: async (jid, payload) => sent.push({ jid, payload }),
  }
  guard.attach(live)
  live.ev.emit('connection.update', { connection: 'open' })
  live.ev.emit('connection.update', { connection: 'open' })
  await new Promise(resolve => setImmediate(resolve))
  assert.equal(sent.length, 1)
  assert.equal(sent[0].jid, 'startup-test@s.whatsapp.net')
  assert.match(sent[0].payload.text, /KENTECH AI is online/)
})

test('uses the deployer bot username and prefix in the startup message', async t => {
  const previousName = process.env.BOT_NAME
  const previousPrefix = process.env.PREFIX
  process.env.BOT_NAME = 'Customer Bot'
  process.env.PREFIX = '!'
  t.after(() => {
    if (previousName === undefined) delete process.env.BOT_NAME
    else process.env.BOT_NAME = previousName
    if (previousPrefix === undefined) delete process.env.PREFIX
    else process.env.PREFIX = previousPrefix
  })
  const { guard } = setup(t)
  const sent = []
  const live = {
    ...socket,
    user: { id: 'custom-startup@s.whatsapp.net' },
    ev: new EventEmitter(),
    sendMessage: async (jid, payload) => sent.push({ jid, payload }),
  }
  guard.attach(live)
  live.ev.emit('connection.update', { connection: 'open' })
  await new Promise(resolve => setImmediate(resolve))
  assert.match(sent[0].payload.text, /Customer Bot is online/)
  assert.match(sent[0].payload.text, /Use !menu/)
})
