const { test } = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { EventEmitter } = require('node:events')
const { createGuard } = require('../download-group-guard')

const group = '123@g.us'
const other = '456@g.us'
const sender = '200@s.whatsapp.net'
const socket = { user: { id: '100:2@s.whatsapp.net', lid: '101@lid' } }
const raw = (overrides = {}) => ({ key: { remoteJid: group, participant: sender, id: '3EB0123456789012345678', ...overrides }, message: { conversation: 'download ready' } })
function setup(t) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'botguard-test-'))
  fs.writeFileSync(path.join(root, 'auto-download-groups.json'), JSON.stringify([group]))
  t.after(() => fs.rmSync(root, { recursive: true, force: true }))
  return { root, guard: createGuard(root) }
}

test('detects bot replies only in protected groups and exempts the owner', t => {
  const { guard } = setup(t)
  assert.equal(guard.shouldBlock(raw(), socket), true)
  assert.equal(guard.shouldBlock(raw({ remoteJid: other }), socket), false)
  assert.equal(guard.shouldBlock(raw({ fromMe: true }), socket), false)
  assert.equal(guard.shouldBlock(raw({ participant: '101@lid' }), socket), false)
  assert.equal(guard.shouldBlock(raw({ participant: '100@s.whatsapp.net' }), socket), false)
})

test('ordinary group members can still post download links', t => {
  const { guard } = setup(t)
  const message = raw({ id: 'NORMALPHONE123' })
  message.message.conversation = 'https://vt.tiktok.com/ZSqFGMM6Y/'
  assert.equal(guard.shouldBlock(message, socket), false)
})

test('detected senders remain blocked after restart, with a persistent release override', t => {
  const { guard, root } = setup(t)
  guard.shouldBlock(raw({ participantAlt: '201@lid' }), socket, true)
  const restarted = createGuard(root)
  assert.equal(restarted.shouldBlock(raw({ id: 'NORMALPHONE123' }), socket), true)
  restarted.configure(group, 'release', [sender, '201@lid'])
  assert.equal(createGuard(root).shouldBlock(raw(), socket), false)
  restarted.configure(group, 'block', [sender])
  assert.equal(restarted.shouldBlock(raw(), socket), true)
})

test('release-all disables enforcement and on restores it', t => {
  const { guard, root } = setup(t)
  guard.configure(group, 'off')
  assert.equal(createGuard(root).shouldBlock(raw(), socket), false)
  guard.configure(group, 'on')
  assert.equal(guard.shouldBlock(raw(), socket), true)
})

test('deletes new bot messages silently, without replaying history or touching own video', async t => {
  const { guard } = setup(t)
  const deleted = []
  const live = { ...socket, ev: new EventEmitter(), sendMessage: async (jid, payload) => deleted.push({ jid, payload }) }
  guard.attach(live)
  live.ev.emit('messages.upsert', { type: 'append', messages: [raw()] })
  live.ev.emit('messages.upsert', { type: 'notify', messages: [raw(), raw({ fromMe: true }), raw({ remoteJid: other })] })
  await new Promise(resolve => setImmediate(resolve))
  assert.equal(deleted.length, 1)
  assert.deepEqual(deleted[0].payload, { delete: { ...raw().key, fromMe: false } })
})

test('bot captions are detected inside wrapped video messages', t => {
  const { guard } = setup(t)
  const message = raw({ id: 'NORMALPHONE123' })
  message.message = { ephemeralMessage: { message: { videoMessage: { caption: 'VIDEO GENERATED BY OTHER BOT' } } } }
  assert.equal(guard.shouldBlock(message, socket), true)
})

test('deletes group statuses from non-admins while allowing admins and the owner', async t => {
  const { root } = setup(t)
  const deleted = []
  const live = {
    ...socket,
    ev: new EventEmitter(),
    groupMetadata: async () => ({ participants: [{ id: '100@s.whatsapp.net', admin: 'admin' }] }),
    sendMessage: async (jid, payload) => deleted.push({ jid, payload }),
  }
  const guard = createGuard(root, { getAntiGstatus: async () => ({ enabled: true, jids: [] }) })
  guard.attach(live)
  const status = overrides => raw({ remoteJid: 'status@broadcast', statusJidList: [group], ...overrides })
  live.ev.emit('messages.upsert', { type: 'notify', messages: [status()] })
  live.ev.emit('messages.upsert', { type: 'notify', messages: [status({ participant: '300@s.whatsapp.net' })] })
  live.ev.emit('messages.upsert', { type: 'notify', messages: [status({ participant: socket.user.id, fromMe: true })] })
  live.groupMetadata = async () => ({ participants: [{ id: '300@s.whatsapp.net', admin: 'admin' }] })
  await new Promise(resolve => setImmediate(resolve))
  assert.equal(deleted.length, 1)
  assert.equal(deleted[0].jid, 'status@broadcast')
})

test('does not delete statuses in ignored groups', async t => {
  const { root } = setup(t)
  const deleted = []
  const live = {
    ...socket,
    ev: new EventEmitter(),
    groupMetadata: async () => ({ participants: [] }),
    sendMessage: async (jid, payload) => deleted.push({ jid, payload }),
  }
  const guard = createGuard(root, { getAntiGstatus: async () => ({ enabled: true, jids: [group] }) })
  guard.attach(live)
  live.ev.emit('messages.upsert', { type: 'notify', messages: [raw({ remoteJid: 'status@broadcast', statusJidList: [group] })] })
  await new Promise(resolve => setImmediate(resolve))
  assert.equal(deleted.length, 0)
})
